### PR TITLE
Scan classpaths for extensions only once

### PR DESCRIPTION
**Pull request by bszeman9**
See details in #98

Summary
==============================

Scan classpaths for extensions only once not per test suite class.

Additional Details
==============================

#98 

Checklist
==============================

Testing
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

* [x] I have manually verified that my code changes do the right thing.
* [x] I have run the tests and verified that my changes do not introduce any regressions.
* [x] I have written unit tests to verify that my code changes do the right thing and to protect my code against regressions

Documentation
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

* [x] I have updated the "Unreleased" section of `CHANGELOG.md` with a brief description of my changes.
* [x] I have updated code comments - both GroovyDoc/JavaDoc-style comments and inline comments - where appropriate.
* [x] I have read `CONTRIBUTING.md` and have followed its guidance.

### CODE REVIEW

**Comment by deblaci** [comment]
Well done Bence, I can't wait for try it. :)

**Comment by dpalfi** [comment]
1 if and it's a lot faster, GJ

**Review by awittha — APPROVED** [review]
Thank you!

**Comment by rh-hemartin** [comment]
Hey! Any chance of this being released?

**Pull request merged**
